rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  # - ruby-head  # test again later: RedCloth not compiling
  - jruby-head
  - ree
branches:
  only:
    - theme-loading
script: "rake test" # test:scanners"
